// Rigi
// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: Copyright (c) Rigi contributors

// Prints the app graph island table (src/lib/gpu/app-graph/manifest.ts) as Markdown (WAG W0.3).
//   npx tsx scripts/gpu/app-graph-table.ts            # to stdout
//   npx tsx scripts/gpu/app-graph-table.ts --write    # → research_notes/whole-app-graph-2026-10-01/islands.generated.md
//   npx tsx scripts/gpu/app-graph-table.ts --check    # exit 1 when that file is stale (fast tier)
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import {
	GPU_MODULES,
	ISLANDS,
	isRemote,
	TEST_GRAPH_GROUPS,
} from "../../src/lib/gpu/app-graph/manifest";

const OUT = join(
	import.meta.dirname,
	"../../research_notes/whole-app-graph-2026-10-01/islands.generated.md",
);

/** Escape a table cell (pipes, newlines). */
const cell = (s: string) => s.replace(/\|/g, "\\|").replace(/\n/g, " ");
const code = (xs: readonly string[]) =>
	xs.length ? xs.map((x) => `\`${x}\``).join(", ") : "–";

export function islandTable(): string {
	const lines: string[] = [
		"<!-- Generated by scripts/gpu/app-graph-table.ts from src/lib/gpu/app-graph/manifest.ts. Do not edit; run `npx tsx scripts/gpu/app-graph-table.ts --write`. -->",
		"",
		"# App graph islands (generated)",
		"",
		"Islands I0–I12 as in `dataflow-map.md` §5, with the GPU modules the manifest registers for each. `groups` are core `cachedGraph` groups (the fast-tier check `app-graph` keeps them equal to the code). A module whose realms are all workers is **remote**: its graphs live in another realm and `/dev/graph` cannot list them.",
		"",
		"## Islands",
		"",
		"| island | name | cadence | realms today | modules | cachedGraph groups |",
		"|---|---|---|---|---|---|",
	];
	for (const i of ISLANDS) {
		const mods = GPU_MODULES.filter((m) => m.island === i.id);
		lines.push(
			`| ${i.id} | ${cell(i.name)}${i.graph ? "" : " (not a graph)"} | ${i.cadence.join(", ")} | ${i.realms.join(", ")} | ${mods.map((m) => m.id).join(", ") || "–"} | ${code(mods.flatMap((m) => m.groups))} |`,
		);
	}
	lines.push(
		"",
		"## Modules",
		"",
		"| module | island | status | realm | cadence | groups | resources | readbacks |",
		"|---|---|---|---|---|---|---|---|",
	);
	for (const m of GPU_MODULES) {
		const realm = `${m.realms.join(", ")}${isRemote(m) ? " (remote)" : ""}`;
		const groups = [
			...m.groups.map((g) => `\`${g}\``),
			...(m.graphIdPrefixes ?? []).map((p) => `\`${p}*\` (uncached)`),
		];
		lines.push(
			`| ${m.id} | ${m.island} | ${m.status} | ${realm} | ${m.cadence} | ${groups.join(", ") || "–"} | ${cell(m.resources.join("; ") || "–")} | ${cell(m.readbacks.join("; ") || "–")} |`,
		);
	}
	const notes = GPU_MODULES.filter((m) => m.notes);
	if (notes.length) {
		lines.push("", "## Notes", "");
		for (const m of notes) lines.push(`- **${m.id}**: ${m.notes}`);
	}
	lines.push(
		"",
		`Test and bench groups (not islands): ${code(TEST_GRAPH_GROUPS)}.`,
		"",
	);
	return lines.join("\n");
}

const md = islandTable();
const arg = process.argv[2];
if (arg === "--write") {
	writeFileSync(OUT, md);
	console.log(`wrote ${OUT}`);
} else if (arg === "--check") {
	let current = "";
	try {
		current = readFileSync(OUT, "utf8");
	} catch {}
	if (current !== md) {
		console.log(
			"FAIL islands.generated.md is stale: run npx tsx scripts/gpu/app-graph-table.ts --write",
		);
		process.exit(1);
	}
	console.log("PASS islands.generated.md is current");
} else process.stdout.write(md);
