// Rigi
// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: Copyright (c) Rigi contributors

// Generates src/lib/live/wmmCoefficients.ts from the official WMM2025 coefficient file (WMM.COF).
//   curl -sLO https://www.ncei.noaa.gov/sites/default/files/2024-12/WMM2025COF.zip && unzip WMM2025COF.zip
//   npx tsx scripts/live/wmm-gen.ts WMM2025COF/WMM2025.COF
// The World Magnetic Model is a US/UK government work (NOAA NCEI and BGS), public domain.

import { readFileSync, writeFileSync } from "node:fs";

const inputPath = process.argv[2];
if (!inputPath) throw new Error("usage: wmm-gen.ts <WMM.COF>");
const lines = readFileSync(inputPath, "utf8").split(/\r?\n/);
const header = lines[0].trim().split(/\s+/);
const epoch = Number(header[0]);
const modelName = header[1];
const releaseDate = header[2];
const rows: string[] = [];
let maxDegree = 0;
for (const line of lines.slice(1)) {
	const fields = line.trim().split(/\s+/);
	// the file ends with lines of 9s
	if (fields.length !== 6) continue;
	const [degree, order] = fields.slice(0, 2).map(Number);
	maxDegree = Math.max(maxDegree, degree);
	const values = fields.slice(2).map(Number);
	rows.push(`\t[${degree}, ${order}, ${values.join(", ")}],`);
}
const output = `// Rigi
// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: Copyright (c) Rigi contributors

// GENERATED by scripts/live/wmm-gen.ts from the official ${modelName} coefficient file (${releaseDate}).
// World Magnetic Model, NOAA NCEI and BGS, US and UK government work, public domain.
// https://www.ncei.noaa.gov/products/world-magnetic-model

export const WMM_EPOCH = ${epoch};
export const WMM_DEGREE = ${maxDegree};

/** [n, m, g (nT), h (nT), gDot (nT/yr), hDot (nT/yr)] at the model epoch. */
export const WMM_TERMS: readonly (readonly [
	number,
	number,
	number,
	number,
	number,
	number,
])[] = [
${rows.join("\n")}
];
`;
writeFileSync("src/lib/live/wmmCoefficients.ts", output);
console.log(`${rows.length} terms, degree ${maxDegree}, epoch ${epoch}`);
