// A tiny terroir pack for node checks (Thunersee-ish coordinates).
import type { TerroirPack } from "../types";

export const MINI_PACK: TerroirPack = {
	v: 1,
	id: "mini",
	name: "Mini",
	bbox: [7.4, 46.5, 8.1, 46.8],
	created: "2026-10-01",
	sources: [],
	glaciers: [],
	cover: null,
	lithology: null,
	names: [
		{
			name: "Thunersee",
			alt: "Lac de Thoune",
			cls: "lake",
			lat: 46.69,
			lon: 7.7,
			ele: 558,
			lang: "de",
			status: "official",
			src: "swissnames3d",
			areaKm2: 48,
		},
		{
			name: "Niesen",
			cls: "peak",
			lat: 46.645,
			lon: 7.651,
			ele: 2362,
			lang: "de",
			status: "official",
			src: "swissnames3d",
			prominence: null,
		},
		{
			name: "Jungfrau",
			cls: "peak-major",
			lat: 46.537,
			lon: 7.962,
			ele: 4158,
			lang: "de",
			status: "official",
			src: "swissnames3d",
		},
		{
			name: "Kleiner Gipfel",
			cls: "peak-minor",
			lat: 46.6,
			lon: 7.8,
			ele: 1700,
			lang: "de",
			status: "official",
			src: "swissnames3d",
		},
		{
			name: "Berner Oberland",
			cls: "region",
			lat: 46.6,
			lon: 7.8,
			ele: null,
			lang: "de",
			status: "official",
			src: "swissnames3d",
			areaKm2: 2500,
		},
		{
			name: "Hohgant",
			cls: "ridge",
			lat: 46.77,
			lon: 7.8,
			ele: null,
			lang: "de",
			status: "official",
			src: "swissnames3d",
		},
	],
};
