// Rigi
// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: Copyright (c) Rigi contributors

// GENERATED by scripts/ontology/gen-realizations.ts from catalogue/concepts.ts. Do not edit; rerun the script.
//
// Rigi's problem space as types. A person brings a PHOTO (capture) of mountains; Rigi recovers the CAMERA
// that took it (eye position, orientation, intrinsics) against the WORLD (DEM terrain, peaks, lakes, trails)
// by matching EVIDENCE seen in the photo (skyline, pins, cues) to what the world predicts from a candidate
// camera (horizon). Solvers produce ESTIMATES, each with provenance and a confidence on its own scale;
// a named resolution policy picks which one is shown. PRESENTATION draws the solved photo (view modes,
// looks, peak labels, Step Inside); INTERCHANGE writes it out; SYSTEM holds renderers, flags and settings.
//
// Every name below is the concept's own word, bound to its canonical realization. Import from here when a
// signature talks about the concept rather than one module's representation of it:
//   import type { Orientation, Horizon, PoseEstimate } from "#/lib/ontology/domain";
// Type-only; nothing here is bundled.
// Not bound (only realized by parked research in lib/geocam): lake.

// ---- capture: what the photographer brought: photos, their metadata, rolls -----------------------

/**
 * Photo: One image plus what the phone recorded with it: time, position, heading, tilt and lens.
 * Canonical: `lib/photos.ts#PhotoMeta`.
 * Other shapes: `lib/upload/exif.ts#LocalPhotoMeta`, `lib/upload/store.ts#PhotoRecord`,
 * `lib/geo/photo-meta.ts#ExifPhotoMeta`.
 */
export type Photo = import("#/lib/photos").PhotoMeta;

/**
 * Raw EXIF: Tags as read from the file before Rigi interprets them (optional everything, magnetic
 * or true heading, 35 mm focal).
 * Canonical: `lib/upload/exif.ts#ExifTags`.
 * Other shapes: `lib/geo/photo-meta.ts#ExifPhotoMeta`.
 */
export type RawExif = import("#/lib/upload/exif").ExifTags;

/**
 * Prior: The camera the phone's sensors imply before any solving: compass heading, tilt, lens and
 * GPS position.
 * Is a {@link Camera}.
 * Canonical: `lib/pose6dof/types.ts#Priors`.
 * Other shapes: `lib/geocam/priors/photo-priors.ts#PriorPhoto`.
 */
export type CameraPrior = import("#/lib/pose6dof/types").Priors;

/**
 * Unknown priors: Which priors are placeholders, not measurements: yaw (no compass), gravity (no
 * pitch/roll), focal (no lens data).
 * Canonical: `lib/integration/unknown-pose.ts#Unknowns`.
 * Other shapes: `lib/upload/exif.ts#LocalPhotoExtras`.
 */
export type PriorUnknowns = import("#/lib/integration/unknown-pose").Unknowns;

/**
 * Roll: Photos of one area, shown as a mosaic, on the map and as a panorama. Grouped on the fly,
 * never stored.
 * Canonical: `lib/roll/types.ts#Roll`.
 * Other shapes: `lib/roll/types.ts#RollPhoto`.
 */
export type Roll = import("#/lib/roll/types").Roll;

/**
 * Viewpoint: Photos taken from (almost) the same spot (250 m); their poses stitch into one
 * panorama.
 * Canonical: `lib/roll/types.ts#Viewpoint`.
 */
export type Viewpoint = import("#/lib/roll/types").Viewpoint;

/**
 * Library: Everything on this device: bundled samples, the demo trip, and uploads in IndexedDB.
 * Canonical: `lib/upload/index.ts#LocalPhotoSummary`.
 */
export type Library = import("#/lib/upload/index").LocalPhotoSummary;

// ---- world: the terrain and mapped features the photo shows --------------------------------------

/**
 * Region: A ~20 km neighbourhood of mapped features (peaks, trails, water names, lakes) around one
 * or more photos.
 * Canonical: `lib/photos.ts#RegionData`.
 * Other shapes: `lib/upload/region.ts#LocalRegion`.
 */
export type Region = import("#/lib/photos").RegionData;

/**
 * Mapped feature: Something named on the map that can appear in a photo.
 * Canonical: `lib/overpass.ts#OsmElement`.
 */
export type Feature = import("#/lib/overpass").OsmElement;

/**
 * Peak: A named summit from OpenStreetMap, with its height and, where known, prominence.
 * Frame: wgs84; ele in metres MSL.
 * Is a {@link Feature}.
 * Canonical: `lib/geo/peaks.ts#Peak`.
 * Other shapes: `lib/photos.ts#RegionPeak`, `lib/picker/candidates.ts#PoolPeak`,
 * `lib/export/geojson.ts#GeoJsonPeak`.
 */
export type Peak = import("#/lib/geo/peaks").Peak;

/**
 * Trail: A mapped path with an SAC difficulty class, drawn on the terrain.
 * Frame: coords are [lon, lat] pairs (LonLatPair), unlike RegionData.center [lat, lon].
 * Is a {@link Feature}.
 * Canonical: `lib/photos.ts#RegionTrail`.
 */
export type Trail = import("#/lib/photos").RegionTrail;

/**
 * Terrain: The ground surface: heights above sea level, read from tiles that get coarser with
 * distance.
 * Frame: heights MSL (≈ EGM2008).
 * Canonical: `lib/geo/terrain.ts#TerrainSampler`.
 */
export type Terrain = import("#/lib/geo/terrain").TerrainSampler;

/**
 * DEM source: A tiled height dataset, Mapterhorn or Terrarium; nearer ground gets finer tiles.
 * Canonical: `lib/dem/sources.ts#DemSource`.
 */
export type DemSource = import("#/lib/dem/sources").DemSource;

/**
 * DEM tile: One z/x/y height raster (row 0 = north), possibly an ancestor stand-in.
 * Frame: web-mercator slippy tile.
 * Canonical: `lib/dem/tiles.ts#TileKey`.
 * Other shapes: `lib/dem/load.ts#DemRaster`.
 */
export type DemTile = import("#/lib/dem/tiles").TileKey;

/**
 * 3D Tiles source: Photogrammetry / building tiles drawn in Step Inside (swisstopo MSL, Google
 * ellipsoidal; Google is display-only).
 * Canonical: `lib/tiles3d/config.ts#Tiles3DSource`.
 */
export type Tiles3dSource = import("#/lib/tiles3d/config").Tiles3DSource;

// ---- camera: where the camera was and how it pointed ---------------------------------------------

/**
 * Camera: Everything needed to project the world into the photo: orientation, eye position and
 * intrinsics, on an image size.
 * Canonical: `lib/concord/core/types.ts#CameraX`.
 * Other shapes: `lib/geo/camera.ts#Camera`, `lib/export/camera.ts#CameraModel`,
 * `lib/export/camera.ts#CameraInput`, `lib/deck-webgpu/camera.ts#CameraState`.
 */
export type Camera = import("#/lib/concord/core/types").CameraX;

/**
 * Pose: Where the camera pointed: yaw (true heading, clockwise from north), pitch (up +), roll
 * (right side down +), and vertical field of view. Degrees. Carries NO position.
 * Frame: enu-eye; degrees.
 * Canonical: `lib/camera/index.ts#Pose`.
 * Other shapes: `lib/geo/camera.ts#CameraParams`.
 */
export type Orientation = import("#/lib/camera/index").Pose;

/**
 * Intrinsics: The lens model beyond vfov: focal scale, k1 radial distortion, principal point
 * (normalised). Default: square pixels, centred, no distortion.
 * Canonical: `lib/concord/core/types.ts#Intrinsics`.
 * Other shapes: `lib/nearfield/geom.ts#IntrinsicsNorm`.
 */
export type Intrinsics = import("#/lib/concord/core/types").Intrinsics;

/**
 * Eye: The camera centre: lat/lon plus height (MSL). Usually GPS horizontally; vertically the eye
 * rule unless solved.
 * Frame: wgs84 + MSL; engine ENU origin (lat, lon, h=0).
 * Canonical: `lib/geodesy.ts#EnuFrame`.
 */
export type Eye = import("#/lib/geodesy").EnuFrame;

/**
 * Position: A WGS84 point with an explicit height datum.
 * Canonical: `lib/geodesy.ts#LatLon`.
 * Other shapes: `lib/ontology/core/geometry.ts#GeoPoint`.
 */
export type GeoPosition = import("#/lib/geodesy").LatLon;

/**
 * Eye rule: How high the camera sits without a solve: the GPS altitude, but at least standing
 * height above the ground.
 * Canonical: `lib/concord/priors/altitude.ts#EyePrior`.
 */
export type EyeRule = import("#/lib/concord/priors/altitude").EyePrior;

// ---- evidence: what is observed in the photo and matched to the world ----------------------------

/**
 * Horizon: The skyline the terrain predicts: the highest visible ridge in every direction.
 * Frame: azel; elevation degrees at azimuth i·step.
 * Canonical: `lib/geo/horizon.ts#HorizonProfile`.
 * Other shapes: `lib/pose6dof/eye.ts#EyeHorizon`, `lib/horizon-fast/march.ts#FastHorizonProfile`,
 * `lib/peakfix/layered.ts#LayeredHorizon`.
 */
export type Horizon = import("#/lib/geo/horizon").HorizonProfile;

/**
 * Skyline: The line between sky and terrain as seen in the photo.
 * Frame: image; rows in working px (v down).
 * Canonical: `lib/geo/skyline.ts#SkylineObservation`.
 * Other shapes: `lib/pose6dof/eye.ts#SkylineSample`.
 */
export type Skyline = import("#/lib/geo/skyline").SkylineObservation;

/**
 * Sky mask: Per-pixel P(sky)·255, row 0 = top, from the segmentation model or a colour fallback.
 * Canonical: `lib/sky/index.ts#SkyMask`.
 * Other shapes: `lib/ontology/core/geometry.ts#ByteMask`.
 */
export type SkyMask = import("#/lib/sky/index").SkyMask;

/**
 * Foreground mask: Per-pixel person/foreground mask (255 = person), row 0 = top: protected from
 * terrain blending and excluded from skyline evidence.
 * Canonical: `lib/segment.ts#ForegroundMask`.
 */
export type ForegroundMask = import("#/lib/segment").ForegroundMask;

/**
 * Correspondence: An image point tied to the world: a 3D point, a direction, a level or an
 * azimuth. The input to pin solves and MAP.
 * Frame: image norm (u, v) ↔ ENU or azel.
 * Canonical: `lib/pose6dof/types.ts#Correspondence`.
 * Other shapes: `lib/geocam/map/factors.ts#Corr2D3D`, `lib/geo/control-points.ts#ControlPoint`.
 */
export type Correspondence = import("#/lib/pose6dof/types").Correspondence;

/**
 * Pin: A tap that ties a named peak to a point in the photo. One pin sets direction, two add tilt,
 * three add the lens.
 * Is a {@link Correspondence}.
 * Canonical: `lib/align.ts#Pin`.
 */
export type Pin = import("#/lib/align").Pin;

/**
 * Cue: An automatically found or curated correspondence of one evidence family (point, edge,
 * level, shore), with residual and confidence.
 * Is a {@link Correspondence}.
 * Canonical: `lib/concord/core/types.ts#Cue`.
 * Other shapes: `lib/concord/core/types.ts#InteriorPin`.
 */
export type Cue = import("#/lib/concord/core/types").Cue;

// ---- estimate: solving, judging and choosing camera estimates ------------------------------------

/**
 * Pose estimate: Where the camera pointed (sometimes where it stood), plus who found it, from
 * what, and how sure.
 * Canonical: `lib/roll/types.ts#SolvedPose`.
 * Other shapes: `lib/integration/second-opinion.ts#AppAlign`,
 * `lib/integration/unknown-pose.ts#UnknownPoseOutcome`,
 * `lib/integration/second-opinion.ts#SecondOpinion`, `lib/demo/index.ts#DemoPose`.
 */
export type PoseEstimate = import("#/lib/roll/types").SolvedPose;

/**
 * Candidate: One of several alternative pose estimates offered for choice (picker, cascade seeds,
 * autoAlign alternatives).
 * Is a {@link PoseEstimate}.
 * Canonical: `lib/picker/candidates.ts#Candidate`.
 * Other shapes: `lib/refine/index.ts#RefineMode`.
 */
export type Candidate = import("#/lib/picker/candidates").Candidate;

/**
 * Solve result: A solver's full output: the estimate plus residuals, inliers, uncertainty and
 * diagnostics.
 * Canonical: `lib/align.ts#AlignResult`.
 * Other shapes: `lib/geo/solve.ts#SkylineSolveResult`, `lib/pose6dof/types.ts#GcpSolveResult`,
 * `lib/refine/index.ts#RefineResult`, `lib/geocam/core/types.ts#MapResult`,
 * `lib/matcher-client.ts#MatchResult`, `lib/integration/unknown-pose.ts#UnknownPoseResult`.
 */
export type SolveResult = import("#/lib/align").AlignResult;

/**
 * Provenance: How a value is known, on orthogonal axes: agent, method, evidence, role, status,
 * outcome, corroboration, confidence.
 * Canonical: `lib/ontology/core/provenance.ts#Provenance`.
 * Other shapes: `lib/roll/types.ts#PoseSource`.
 */
export type Provenance = import("#/lib/ontology/core/provenance").Provenance;

/**
 * Confidence: A producer's score on its own scale, read as a comparable level
 * (high/medium/low/unknown).
 * Canonical: `lib/ontology/core/confidence.ts#Confidence`.
 * Other shapes: `lib/refine/confidence.ts#RefineConfidence`,
 * `lib/concord/app/confidence.ts#PoseConfidence`.
 */
export type Confidence = import("#/lib/ontology/core/confidence").Confidence;

/**
 * Ground truth: Hand-fitted poses for bundled photos (data/ground-truth.json, quality
 * good/approx/none). Shown as 'fitted'; an oracle in evaluation.
 * Canonical: `lib/roll/roll.ts#GtEntry`.
 */
export type GroundTruth = import("#/lib/roll/roll").GtEntry;

/**
 * Suggestion: A propagated pose offered for a person to accept or dismiss; never HIGH, never an
 * anchor.
 * Is a {@link PoseEstimate}.
 * Canonical: `lib/roll/propagate/store.ts#StoredSuggestion`.
 */
export type Suggestion = import("#/lib/roll/propagate/store").StoredSuggestion;

// ---- presentation: how a solved photo is drawn: modes, looks, labels, layers ---------------------

/**
 * View mode: How terrain and photo combine: Overlay (lines on the photo), Blend (terrain replaces
 * parts of it), In map (3D world).
 * Canonical: `lib/settings.ts#ViewMode`.
 * Other shapes: `lib/style/deck-apply.ts#DeckStyleMode`.
 */
export type ViewMode = import("#/lib/settings").ViewMode;

/**
 * Blend method: How Blend chooses where terrain shows: lens, swipe, distance range, brush.
 * Canonical: `lib/settings.ts#BlendMethod`.
 */
export type BlendMethod = import("#/lib/settings").BlendMethod;

/**
 * Look: The whole visual style of a view (terrain lighting, overlay lines, bands, labels): a
 * preset plus overrides.
 * Canonical: `lib/style/types.ts#ViewStyle`.
 * Other shapes: `lib/style/types.ts#StyleState`.
 */
export type Look = import("#/lib/style/types").ViewStyle;

/**
 * Look preset: A named patch over CLASSIC (classic, minimal, topo-map, night, …).
 * Canonical: `lib/style/types.ts#PresetId`.
 */
export type LookPreset = import("#/lib/style/types").PresetId;

/**
 * Label: A peak projected into the photo, ranked, occlusion-tested and laid out.
 * Canonical: `lib/settings.ts#PeakLabel`.
 * Other shapes: `lib/geo/peaks.ts#PeakLabelPx`, `lib/look/labels/layout.ts#LabelCandidate`.
 */
export type PeakLabel = import("#/lib/settings").PeakLabel;

/**
 * Reveal: The overlay's bloom-in animation on load (presets, duration, glow).
 * Canonical: `lib/reveal/config.ts#RevealConfig`.
 */
export type Reveal = import("#/lib/reveal/config").RevealConfig;

/**
 * Step Inside: The near ground rebuilt in 3D on the terrain; view it from the photo, orbiting,
 * flying or from above.
 * Canonical: `lib/nearfield/types.ts#NearFieldScene`.
 * Other shapes: `lib/nearfield/types.ts#GaussianCloud`.
 */
export type StepInside = import("#/lib/nearfield/types").NearFieldScene;

// ---- interchange: files and formats that leave the app -------------------------------------------

/**
 * Export format: A file Rigi writes for a solved photo (annotated PNG, KMZ, GeoJSON, pose JSON,
 * COLMAP, XMP, splats).
 * Canonical: `lib/export/engine-export.ts#ExportFormat`.
 * Other shapes: `lib/export/splat.ts#SplatExportFormat`.
 */
export type ExportFormat = import("#/lib/export/engine-export").ExportFormat;

/**
 * Pose file: Self-describing pose JSON (schema rigi/pose v1): position with both datums,
 * orientation, K, R|t.
 * Is a {@link ExportFormat}.
 * Canonical: `lib/export/pose-json.ts#PoseJson`.
 */
export type PoseFile = import("#/lib/export/pose-json").PoseJson;

// ---- system: renderers, flags, settings, storage -------------------------------------------------

/**
 * Renderer: An engine that draws terrain behind/over the photo: deck.gl on WebGPU (default where
 * available) or on WebGL (fallback).
 * Canonical: `lib/renderer.ts#Renderer`.
 */
export type Renderer = import("#/lib/renderer").Renderer;

/**
 * Flag: A typed page-level switch (?name=value), read only through lib/flags.
 * Canonical: `lib/flags/index.ts#Flags`.
 */
export type Flag = import("#/lib/flags/index").Flags;

/**
 * View settings: The workspace's per-view knobs (mode, blend method, overlay/replace/world layer
 * choice, opacity, toggles).
 * Canonical: `lib/settings.ts#Settings`.
 */
export type Settings = import("#/lib/settings").Settings;
