// Rigi
// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: Copyright (c) Rigi contributors

// Renderers for the files generated from the concept catalogue (written by
// scripts/ontology/gen-realizations.ts; ontology.check.ts fails when a file on disk is stale):
//  - src/lib/ontology/checks/realizations.ts: every realizedBy key → `import("#/…").Export`. tsc then
//    proves each export exists; the Equal<> assert proves the map and the catalogue list the same keys.
//  - src/lib/ontology/domain.ts: the vocabulary. One type per concept, named after the concept, bound
//    to its canonical realization and documented with the catalogue's definition.
import {
	CONCEPTS,
	type ConceptDef,
	DOMAINS,
	type Domain,
} from "./catalogue/concepts";

const SPDX = `// Rigi
// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: Copyright (c) Rigi contributors
`;

export function renderRealizations(): string {
	const keys = [
		...new Set(Object.values(CONCEPTS).flatMap((c) => [...c.realizedBy])),
	].sort();
	const lines = keys.map((k) => {
		const [path, name] = k.split("#");
		const mod = `#/${path.replace(/\.tsx?$/, "")}`;
		return `\t${JSON.stringify(k)}: import(${JSON.stringify(mod)}).${name};`;
	});
	const out = `${SPDX}
// GENERATED by scripts/ontology/gen-realizations.ts. Do not edit; rerun the script.
// Type-only: never imported by app code, so nothing here is bundled. tsc checks that every concept
// realization in catalogue/concepts.ts names a real exported type, and that this map lists exactly
// the catalogue's keys.
import type { RealizationKey } from "../catalogue/concepts";
import type { Assert, Equal } from "../core/assert";

export type Realizations = {
${lines.join("\n")}
};

export type _realizationsMatchCatalogue = Assert<
	Equal<keyof Realizations, RealizationKey>
>;
`;
	return out;
}

// ---- domain.ts ---------------------------------------------------------------------------------------
/** Parked research (src/lib/geocam) never becomes the canonical product type. */
const RESEARCH = /^lib\/geocam\//;
const pascal = (id: string) =>
	id
		.split("-")
		.map((w) => w[0].toUpperCase() + w.slice(1))
		.join("");
const importOf = (key: string) => {
	const [path, name] = key.split("#");
	return `import(${JSON.stringify(`#/${path.replace(/\.tsx?$/, "")}`)}).${name}`;
};
const wrap = (text: string, prefix: string, width = 100) => {
	const out: string[] = [];
	let line = prefix;
	for (const word of text.split(/\s+/)) {
		if (line.length + word.length + 1 > width && line !== prefix) {
			out.push(line.trimEnd());
			line = prefix;
		}
		line += `${word} `;
	}
	out.push(line.trimEnd());
	return out;
};
export function renderDomain(): string {
	const sections: string[] = [];
	const omitted: string[] = [];
	for (const domain of Object.keys(DOMAINS) as Domain[]) {
		const body: string[] = [];
		for (const [id, concept] of Object.entries(CONCEPTS) as [
			string,
			ConceptDef,
		][]) {
			if (concept.domain !== domain) continue;
			const canonical = concept.realizedBy.find((k) => !RESEARCH.test(k));
			if (!canonical) {
				omitted.push(id);
				continue;
			}
			const others = concept.realizedBy.filter((k) => k !== canonical);
			const doc = [
				...wrap(`${concept.label}: ${concept.definition}`, " * "),
				...(concept.frame ? wrap(`Frame: ${concept.frame}.`, " * ") : []),
				...(concept.is ? [` * Is a {@link ${pascal(concept.is)}}.`] : []),
				` * Canonical: \`${canonical}\`.`,
				...(others.length
					? wrap(
							`Other shapes: ${others.map((k) => `\`${k}\``).join(", ")}.`,
							" * ",
						)
					: []),
			];
			body.push(
				`/**\n${doc.join("\n")}\n */\nexport type ${pascal(id)} = ${importOf(canonical)};`,
			);
		}
		sections.push(
			`// ---- ${domain}: ${DOMAINS[domain]} ${"-".repeat(Math.max(4, 90 - domain.length - DOMAINS[domain].length))}\n\n${body.join("\n\n")}`,
		);
	}
	const domainOut = `${SPDX}
// GENERATED by scripts/ontology/gen-realizations.ts from catalogue/concepts.ts. Do not edit; rerun the script.
//
// Rigi's problem space as types. A person brings a PHOTO (capture) of mountains; Rigi recovers the CAMERA
// that took it (eye position, orientation, intrinsics) against the WORLD (DEM terrain, peaks, lakes, trails)
// by matching EVIDENCE seen in the photo (skyline, pins, cues) to what the world predicts from a candidate
// camera (horizon). Solvers produce ESTIMATES, each with provenance and a confidence on its own scale;
// a named resolution policy picks which one is shown. PRESENTATION draws the solved photo (view modes,
// looks, peak labels, Step Inside); INTERCHANGE writes it out; SYSTEM holds renderers, flags and settings.
//
// Every name below is the concept's own word, bound to its canonical realization. Import from here when a
// signature talks about the concept rather than one module's representation of it:
//   import type { Orientation, Horizon, PoseEstimate } from "#/lib/ontology/domain";
// Type-only; nothing here is bundled.${omitted.length ? `\n// Not bound (only realized by parked research in lib/geocam): ${omitted.join(", ")}.` : ""}

${sections.join("\n\n")}
`;
	return domainOut;
}
