blank_issues_enabled: false
contact_links:
  - name: "Start a Discussion: I have a question / I need help"
    url: https://github.com/BertCh/rigi/discussions
    about: Please ask generic questions or request help in Discussions. "Issues" are for confirmed bugs or approved feature requests.
