"""Writes src/lib/tiles3d/geoid-data.ts: EGM2008 geoid undulation N (m) grids for tiles3d/geoid.ts.

N = h_ellipsoid - H_msl, from PROJ's us_nga_egm08_25 grid (EPSG:4979 -> EPSG:4326+3855), fetched
over the PROJ network CDN. Two grids, int16 centimetres, row-major from (lat0, lon0) north/east:
  · alps   0.1 deg over 43..49 N, 4..18 E (bilinear error vs the 2.5' source <= 0.16 m, p95 0.06 m)
  · global 1 deg (bilinear error in the Alps up to 3.4 m, p95 1.6 m: the fallback outside 'alps')
Run:  python3 -m venv /tmp/geo && /tmp/geo/bin/pip install pyproj numpy && /tmp/geo/bin/python scripts/tiles3d/make-geoid.py
"""
import base64, pathlib
import numpy as np, pyproj
from pyproj import Transformer

pyproj.network.set_network_enabled(True)
t = Transformer.from_crs("EPSG:4979", "EPSG:4326+3855", always_xy=True)

def grid(lat0, lat1, lon0, lon1, step):
    lats = np.arange(lat0, lat1 + 1e-9, step)
    lons = np.arange(lon0, lon1 + 1e-9, step)
    LO, LA = np.meshgrid(lons, lats)
    _, _, h = t.transform(LO.ravel(), LA.ravel(), np.zeros(LO.size))
    n = -np.asarray(h).reshape(LA.shape)
    return dict(lat0=lat0, lon0=lon0, step=step, rows=len(lats), cols=len(lons),
                b64=base64.b64encode(np.round(n * 100).astype("<i2").tobytes()).decode())

grids = {"alps": grid(43, 49, 4, 18, 0.1), "global": grid(-90, 90, -180, 180, 1.0)}
out = ["// GENERATED by scripts/tiles3d/make-geoid.py: EGM2008 undulation N (int16 cm, row-major from lat0/lon0).",
       "export type GeoidGrid = { lat0: number; lon0: number; step: number; rows: number; cols: number; b64: string };"]
for k, g in grids.items():
    meta = ", ".join(f"{a}: {g[a]}" for a in ("lat0", "lon0", "step", "rows", "cols"))
    out.append(f'export const GEOID_{k.upper()}: GeoidGrid = {{ {meta}, b64: "{g["b64"]}" }};')
p = pathlib.Path(__file__).resolve().parents[2] / "src/lib/tiles3d/geoid-data.ts"
p.write_text("\n".join(out) + "\n")
print(p, p.stat().st_size)
