// Rigi
// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: Copyright (c) Rigi contributors

// npx tsx scripts/ontology/gen-realizations.ts — regenerate src/lib/ontology/checks/realizations.ts from
// the concept catalogue (every realizedBy key → `import("#/…").Export`). tsc then proves each export
// exists; the Equal<> assert proves the map and the catalogue list the same keys.
import { writeFileSync } from "node:fs";
import { CONCEPTS } from "../../src/lib/ontology/catalogue/concepts";

const keys = [
	...new Set(Object.values(CONCEPTS).flatMap((c) => [...c.realizedBy])),
].sort();
const lines = keys.map((k) => {
	const [path, name] = k.split("#");
	const mod = `#/${path.replace(/\.tsx?$/, "")}`;
	return `\t${JSON.stringify(k)}: import(${JSON.stringify(mod)}).${name};`;
});
const out = `// GENERATED by scripts/ontology/gen-realizations.ts. Do not edit; rerun the script.
// Type-only: never imported by app code, so nothing here is bundled. tsc checks that every concept
// realization in catalogue/concepts.ts names a real exported type, and that this map lists exactly
// the catalogue's keys.
import type { RealizationKey } from "../catalogue/concepts";
import type { Assert, Equal } from "../core/assert";

export type Realizations = {
${lines.join("\n")}
};

export type _realizationsMatchCatalogue = Assert<
	Equal<keyof Realizations, RealizationKey>
>;
`;
writeFileSync(
	new URL("../../src/lib/ontology/checks/realizations.ts", import.meta.url),
	out,
);
console.log(`realizations: ${keys.length} keys`);
