// Rigi
// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: Copyright (c) Rigi contributors

import { useEffect, useMemo, useRef, useState } from "react";

/**
 * The view south from Rigi Kulm, drawn as depth-layered ridgelines from the DEM
 * (public/brand/rigi-panorama.json, generated by scripts/brand/rigi.ts).
 * Horizontal axis is true bearing; the vertical is exaggerated by VEX.
 */

type Peak = {
	name: string;
	ele: number;
	az: number;
	el: number;
	d: number;
	rank: number;
};
type Panorama = {
	viewpoint: { name: string; lat: number; lon: number; ele: number };
	view: { az0: number; az1: number; elMin: number; elMax: number };
	slabs: number[];
	strokes: number[][];
	skyline: [number, number][];
	peaks: Peak[];
};

export const VEX = 2.5;
const LABEL_BAND = 58; // px above the highest summit reserved for names
const FOCUS_AZ = 196; // bearing kept centred when narrow screens crop the sides

const CARDINAL: Record<number, string> = {
	90: "E",
	135: "SE",
	180: "S",
	225: "SW",
	270: "W",
};

export function RigiPanorama({ className }: { className?: string }) {
	const [data, setData] = useState<Panorama | null>(null);
	const [size, setSize] = useState<{ w: number; h: number } | null>(null);
	const [hover, setHover] = useState<number | null>(null);
	const [shown, setShown] = useState(false);
	const ref = useRef<HTMLDivElement>(null);

	useEffect(() => {
		let live = true;
		fetch("/brand/rigi-panorama.json")
			.then((r) => r.json())
			.then((d: Panorama) => live && setData(d))
			.catch(() => {});
		return () => {
			live = false;
		};
	}, []);

	useEffect(() => {
		const el = ref.current;
		if (!el) return;
		const ro = new ResizeObserver(([e]) =>
			setSize({ w: e.contentRect.width, h: e.contentRect.height }),
		);
		ro.observe(el);
		return () => ro.disconnect();
	}, []);

	useEffect(() => {
		if (!data || !size) return;
		const id = requestAnimationFrame(() => setShown(true));
		return () => cancelAnimationFrame(id);
	}, [data, size]);

	const layout = useMemo(() => {
		if (!data || !size || size.w === 0) return null;
		const { az0, az1, elMin } = data.view;
		const top = Math.max(...data.skyline.map(([, y]) => y)) / 1000;
		// Fill the width; if that leaves the frame short, scale up and crop the sides around FOCUS_AZ.
		let s = size.w / (az1 - az0);
		if ((top - elMin) * s * VEX < size.h - LABEL_BAND)
			s = (size.h - LABEL_BAND) / ((top - elMin) * VEX);
		const ox = Math.min(
			0,
			Math.max(size.w - (az1 - az0) * s, size.w / 2 - (FOCUS_AZ - az0) * s),
		);
		const X = (az: number) => ox + (az - az0) * s;
		const Y = (el: number) => LABEL_BAND + (top - el) * s * VEX;
		const n = data.slabs.length - 1;
		const strokes = data.strokes.map((st, i) => {
			const [slab, ridge] = st;
			let x = st[2];
			let y = st[3];
			let d = `M${X(x / 1000).toFixed(1)} ${Y(y / 1000).toFixed(1)}`;
			for (let k = 4; k < st.length; k += 2) {
				x += st[k];
				y += st[k + 1];
				d += `L${X(x / 1000).toFixed(1)} ${Y(y / 1000).toFixed(1)}`;
			}
			return { key: i, d, t: slab / n, ridge: ridge === 1 };
		});
		// Names: greedily by rank, skipping any that would collide with a placed one.
		const placed: { p: Peak; x: number; y: number; w: number }[] = [];
		for (const p of [...data.peaks].sort((a, b) => a.rank - b.rank)) {
			const x = X(p.az);
			const w = p.name.length * 6.2 + 14;
			if (x < 8 || x + w > size.w - 8) continue;
			if (placed.some((q) => x < q.x + q.w && q.x < x + w)) continue;
			placed.push({ p, x, y: Y(p.el), w });
		}
		const ticks = [];
		for (let az = Math.ceil(az0 / 5) * 5; az <= az1; az += 5) {
			const x = X(az);
			if (x >= 0 && x <= size.w) ticks.push({ az, x });
		}
		return { strokes, placed, ticks, X, s };
	}, [data, size]);

	const hoverAz =
		layout && hover != null && data
			? data.view.az0 + (hover - layout.X(data.view.az0)) / layout.s
			: null;
	const hoverPeak =
		layout && hover != null
			? layout.placed.find((q) => Math.abs(q.x - hover) < 10)?.p.name
			: undefined;

	return (
		<div
			ref={ref}
			className={className}
			onPointerMove={(e) =>
				setHover(e.clientX - e.currentTarget.getBoundingClientRect().left)
			}
			onPointerLeave={() => setHover(null)}
		>
			{layout && size && (
				<svg
					width={size.w}
					height={size.h}
					className="block"
					role="img"
					aria-label={`Computed panorama from ${data?.viewpoint.name}, looking south over the Alps`}
				>
					<defs>
						<linearGradient id="rigi-fade" x1="0" y1="0" x2="0" y2="1">
							<stop offset="0.55" stopColor="#fff" />
							<stop offset="1" stopColor="#fff" stopOpacity="0" />
						</linearGradient>
						<mask id="rigi-mask">
							<rect width={size.w} height={size.h} fill="url(#rigi-fade)" />
						</mask>
					</defs>
					<g
						mask="url(#rigi-mask)"
						fill="none"
						stroke="currentColor"
						strokeLinejoin="round"
						strokeLinecap="round"
					>
						{layout.strokes.map((st) => (
							<path
								key={st.key}
								d={st.d}
								strokeWidth={st.ridge ? 1.25 - 0.55 * st.t : 0.7}
								// Aerial perspective: far layers fade in first and stay faint.
								style={{
									opacity: shown
										? st.ridge
											? 0.92 - 0.55 * st.t
											: 0.4 - 0.2 * st.t
										: 0,
									transition: "opacity 1.4s ease",
									transitionDelay: `${Math.round((1 - st.t) * 900)}ms`,
								}}
							/>
						))}
					</g>
					<g
						className="font-mono"
						style={{
							opacity: shown ? 1 : 0,
							transition: "opacity 1s ease 900ms",
						}}
					>
						{layout.placed.map(({ p, x, y }) => {
							const on = hoverPeak === p.name;
							return (
								<g
									key={p.name}
									className={on ? "text-[var(--rigi-glow)]" : undefined}
								>
									<line
										x1={x}
										x2={x}
										y1={14}
										y2={y - 5}
										stroke="currentColor"
										strokeOpacity={on ? 0.9 : 0.22}
										strokeWidth={0.75}
									/>
									<circle
										cx={x}
										cy={y}
										r={on ? 2.2 : 1.4}
										fill="currentColor"
										fillOpacity={on ? 1 : 0.7}
									/>
									<text
										x={x + 5}
										y={16}
										fontSize={10.5}
										fill="currentColor"
										fillOpacity={on ? 1 : 0.78}
										className="font-sans tracking-wide"
									>
										{p.name}
									</text>
									<text
										x={x + 5}
										y={29}
										fontSize={9.5}
										fill="currentColor"
										fillOpacity={on ? 0.85 : 0.4}
									>
										{p.ele}
										{on ? ` m · ${(p.d / 1000).toFixed(0)} km` : ""}
									</text>
								</g>
							);
						})}
					</g>
					<g className="font-mono" fontSize={9.5} fill="currentColor">
						{layout.ticks.map(({ az, x }) => (
							<g key={az}>
								<line
									x1={x}
									x2={x}
									y1={size.h - (az % 10 ? 4 : 8)}
									y2={size.h}
									stroke="currentColor"
									strokeOpacity={0.35}
									strokeWidth={0.75}
								/>
								{az % 10 === 0 && (
									<text
										x={x}
										y={size.h - 12}
										textAnchor="middle"
										fillOpacity={CARDINAL[az] ? 0.75 : 0.35}
									>
										{CARDINAL[az] ?? `${az}°`}
									</text>
								)}
							</g>
						))}
					</g>
					{hover != null && hoverAz != null && (
						<g
							className="pointer-events-none font-mono text-[var(--rigi-glow)]"
							fontSize={9.5}
						>
							<line
								x1={hover}
								x2={hover}
								y1={LABEL_BAND - 16}
								y2={size.h - 24}
								stroke="currentColor"
								strokeOpacity={0.45}
								strokeWidth={0.75}
							/>
							<text x={hover + 5} y={size.h - 26} fill="currentColor">
								{(((hoverAz % 360) + 360) % 360).toFixed(1)}°
							</text>
						</g>
					)}
				</svg>
			)}
		</div>
	);
}
