// Rigi
// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: Copyright (c) Rigi contributors

import mark from "./rigi-mark.json";

/** The Rigi mark: contour lines of the Rigi Kulm summit (1550–1780 m, swissALTI3D), generated by scripts/brand/rigi.ts. */
export function RigiMark({
	className,
	title = "Rigi",
}: {
	className?: string;
	title?: string;
}) {
	const [x, y, side] = mark.box;
	const sw = side / 64;
	const last = mark.paths.length - 1;
	return (
		<svg
			viewBox={`${x} ${y} ${side} ${side}`}
			className={className}
			role="img"
			aria-label={title}
		>
			{mark.paths.map((p, i) => (
				<path
					key={p.level}
					d={p.d}
					fill="none"
					stroke="currentColor"
					strokeLinejoin="round"
					strokeWidth={(i === last ? 2.6 : 1.5) * sw}
					strokeOpacity={0.45 + (0.55 * i) / last}
				/>
			))}
		</svg>
	);
}
