/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BaselineRouteImport } from './routes/baseline'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as AtlasIndexRouteImport } from './routes/atlas.index'
import { Route as AtlasConceptRouteImport } from './routes/atlas.$concept'
import { Route as DevExportRollRouteImport } from './routes/dev.export-roll'
import { Route as DevGraphRouteImport } from './routes/dev.graph'
import { Route as DevHowSceneRouteImport } from './routes/dev.how-scene'
import { Route as LabDeckSplatsRouteImport } from './routes/lab.deck-splats'
import { Route as LabDeckWebgpuRouteImport } from './routes/lab.deck-webgpu'
import { Route as LabGenerateRouteImport } from './routes/lab.generate'
import { Route as LabSplatsRouteImport } from './routes/lab.splats'
import { Route as PhotoIdRouteImport } from './routes/photo.$id'
import { Route as RollIndexRouteImport } from './routes/roll.index'
import { Route as RollIdRouteImport } from './routes/roll.$id'
import { Route as RollImportRouteImport } from './routes/roll.import'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BaselineRoute = BaselineRouteImport.update({
  id: '/baseline',
  path: '/baseline',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasIndexRoute = AtlasIndexRouteImport.update({
  id: '/atlas/',
  path: '/atlas/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasConceptRoute = AtlasConceptRouteImport.update({
  id: '/atlas/$concept',
  path: '/atlas/$concept',
  getParentRoute: () => rootRouteImport,
} as any)
const DevExportRollRoute = DevExportRollRouteImport.update({
  id: '/dev/export-roll',
  path: '/dev/export-roll',
  getParentRoute: () => rootRouteImport,
} as any)
const DevGraphRoute = DevGraphRouteImport.update({
  id: '/dev/graph',
  path: '/dev/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const DevHowSceneRoute = DevHowSceneRouteImport.update({
  id: '/dev/how-scene',
  path: '/dev/how-scene',
  getParentRoute: () => rootRouteImport,
} as any)
const LabDeckSplatsRoute = LabDeckSplatsRouteImport.update({
  id: '/lab/deck-splats',
  path: '/lab/deck-splats',
  getParentRoute: () => rootRouteImport,
} as any)
const LabDeckWebgpuRoute = LabDeckWebgpuRouteImport.update({
  id: '/lab/deck-webgpu',
  path: '/lab/deck-webgpu',
  getParentRoute: () => rootRouteImport,
} as any)
const LabGenerateRoute = LabGenerateRouteImport.update({
  id: '/lab/generate',
  path: '/lab/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const LabSplatsRoute = LabSplatsRouteImport.update({
  id: '/lab/splats',
  path: '/lab/splats',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotoIdRoute = PhotoIdRouteImport.update({
  id: '/photo/$id',
  path: '/photo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RollIndexRoute = RollIndexRouteImport.update({
  id: '/roll/',
  path: '/roll/',
  getParentRoute: () => rootRouteImport,
} as any)
const RollIdRoute = RollIdRouteImport.update({
  id: '/roll/$id',
  path: '/roll/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RollImportRoute = RollImportRouteImport.update({
  id: '/roll/import',
  path: '/roll/import',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/baseline': typeof BaselineRoute
  '/library': typeof LibraryRoute
  '/upload': typeof UploadRoute
  '/atlas/$concept': typeof AtlasConceptRoute
  '/dev/export-roll': typeof DevExportRollRoute
  '/dev/graph': typeof DevGraphRoute
  '/dev/how-scene': typeof DevHowSceneRoute
  '/lab/deck-splats': typeof LabDeckSplatsRoute
  '/lab/deck-webgpu': typeof LabDeckWebgpuRoute
  '/lab/generate': typeof LabGenerateRoute
  '/lab/splats': typeof LabSplatsRoute
  '/photo/$id': typeof PhotoIdRoute
  '/roll/$id': typeof RollIdRoute
  '/roll/import': typeof RollImportRoute
  '/atlas/': typeof AtlasIndexRoute
  '/roll/': typeof RollIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/baseline': typeof BaselineRoute
  '/library': typeof LibraryRoute
  '/upload': typeof UploadRoute
  '/atlas/$concept': typeof AtlasConceptRoute
  '/dev/export-roll': typeof DevExportRollRoute
  '/dev/graph': typeof DevGraphRoute
  '/dev/how-scene': typeof DevHowSceneRoute
  '/lab/deck-splats': typeof LabDeckSplatsRoute
  '/lab/deck-webgpu': typeof LabDeckWebgpuRoute
  '/lab/generate': typeof LabGenerateRoute
  '/lab/splats': typeof LabSplatsRoute
  '/photo/$id': typeof PhotoIdRoute
  '/roll/$id': typeof RollIdRoute
  '/roll/import': typeof RollImportRoute
  '/atlas': typeof AtlasIndexRoute
  '/roll': typeof RollIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/baseline': typeof BaselineRoute
  '/library': typeof LibraryRoute
  '/upload': typeof UploadRoute
  '/atlas/$concept': typeof AtlasConceptRoute
  '/dev/export-roll': typeof DevExportRollRoute
  '/dev/graph': typeof DevGraphRoute
  '/dev/how-scene': typeof DevHowSceneRoute
  '/lab/deck-splats': typeof LabDeckSplatsRoute
  '/lab/deck-webgpu': typeof LabDeckWebgpuRoute
  '/lab/generate': typeof LabGenerateRoute
  '/lab/splats': typeof LabSplatsRoute
  '/photo/$id': typeof PhotoIdRoute
  '/roll/$id': typeof RollIdRoute
  '/roll/import': typeof RollImportRoute
  '/atlas/': typeof AtlasIndexRoute
  '/roll/': typeof RollIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/baseline'
    | '/library'
    | '/upload'
    | '/atlas/$concept'
    | '/dev/export-roll'
    | '/dev/graph'
    | '/dev/how-scene'
    | '/lab/deck-splats'
    | '/lab/deck-webgpu'
    | '/lab/generate'
    | '/lab/splats'
    | '/photo/$id'
    | '/roll/$id'
    | '/roll/import'
    | '/atlas/'
    | '/roll/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/baseline'
    | '/library'
    | '/upload'
    | '/atlas/$concept'
    | '/dev/export-roll'
    | '/dev/graph'
    | '/dev/how-scene'
    | '/lab/deck-splats'
    | '/lab/deck-webgpu'
    | '/lab/generate'
    | '/lab/splats'
    | '/photo/$id'
    | '/roll/$id'
    | '/roll/import'
    | '/atlas'
    | '/roll'
  id:
    | '__root__'
    | '/'
    | '/baseline'
    | '/library'
    | '/upload'
    | '/atlas/$concept'
    | '/dev/export-roll'
    | '/dev/graph'
    | '/dev/how-scene'
    | '/lab/deck-splats'
    | '/lab/deck-webgpu'
    | '/lab/generate'
    | '/lab/splats'
    | '/photo/$id'
    | '/roll/$id'
    | '/roll/import'
    | '/atlas/'
    | '/roll/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BaselineRoute: typeof BaselineRoute
  LibraryRoute: typeof LibraryRoute
  UploadRoute: typeof UploadRoute
  AtlasConceptRoute: typeof AtlasConceptRoute
  DevExportRollRoute: typeof DevExportRollRoute
  DevGraphRoute: typeof DevGraphRoute
  DevHowSceneRoute: typeof DevHowSceneRoute
  LabDeckSplatsRoute: typeof LabDeckSplatsRoute
  LabDeckWebgpuRoute: typeof LabDeckWebgpuRoute
  LabGenerateRoute: typeof LabGenerateRoute
  LabSplatsRoute: typeof LabSplatsRoute
  PhotoIdRoute: typeof PhotoIdRoute
  RollIdRoute: typeof RollIdRoute
  RollImportRoute: typeof RollImportRoute
  AtlasIndexRoute: typeof AtlasIndexRoute
  RollIndexRoute: typeof RollIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baseline': {
      id: '/baseline'
      path: '/baseline'
      fullPath: '/baseline'
      preLoaderRoute: typeof BaselineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas/': {
      id: '/atlas/'
      path: '/atlas'
      fullPath: '/atlas/'
      preLoaderRoute: typeof AtlasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas/$concept': {
      id: '/atlas/$concept'
      path: '/atlas/$concept'
      fullPath: '/atlas/$concept'
      preLoaderRoute: typeof AtlasConceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/export-roll': {
      id: '/dev/export-roll'
      path: '/dev/export-roll'
      fullPath: '/dev/export-roll'
      preLoaderRoute: typeof DevExportRollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/graph': {
      id: '/dev/graph'
      path: '/dev/graph'
      fullPath: '/dev/graph'
      preLoaderRoute: typeof DevGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/how-scene': {
      id: '/dev/how-scene'
      path: '/dev/how-scene'
      fullPath: '/dev/how-scene'
      preLoaderRoute: typeof DevHowSceneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/deck-splats': {
      id: '/lab/deck-splats'
      path: '/lab/deck-splats'
      fullPath: '/lab/deck-splats'
      preLoaderRoute: typeof LabDeckSplatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/deck-webgpu': {
      id: '/lab/deck-webgpu'
      path: '/lab/deck-webgpu'
      fullPath: '/lab/deck-webgpu'
      preLoaderRoute: typeof LabDeckWebgpuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/generate': {
      id: '/lab/generate'
      path: '/lab/generate'
      fullPath: '/lab/generate'
      preLoaderRoute: typeof LabGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/splats': {
      id: '/lab/splats'
      path: '/lab/splats'
      fullPath: '/lab/splats'
      preLoaderRoute: typeof LabSplatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photo/$id': {
      id: '/photo/$id'
      path: '/photo/$id'
      fullPath: '/photo/$id'
      preLoaderRoute: typeof PhotoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roll/': {
      id: '/roll/'
      path: '/roll'
      fullPath: '/roll/'
      preLoaderRoute: typeof RollIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roll/$id': {
      id: '/roll/$id'
      path: '/roll/$id'
      fullPath: '/roll/$id'
      preLoaderRoute: typeof RollIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roll/import': {
      id: '/roll/import'
      path: '/roll/import'
      fullPath: '/roll/import'
      preLoaderRoute: typeof RollImportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BaselineRoute: BaselineRoute,
  LibraryRoute: LibraryRoute,
  UploadRoute: UploadRoute,
  AtlasConceptRoute: AtlasConceptRoute,
  DevExportRollRoute: DevExportRollRoute,
  DevGraphRoute: DevGraphRoute,
  DevHowSceneRoute: DevHowSceneRoute,
  LabDeckSplatsRoute: LabDeckSplatsRoute,
  LabDeckWebgpuRoute: LabDeckWebgpuRoute,
  LabGenerateRoute: LabGenerateRoute,
  LabSplatsRoute: LabSplatsRoute,
  PhotoIdRoute: PhotoIdRoute,
  RollIdRoute: RollIdRoute,
  RollImportRoute: RollImportRoute,
  AtlasIndexRoute: AtlasIndexRoute,
  RollIndexRoute: RollIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
