/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BaselineRouteImport } from './routes/baseline'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as PhotoIdRouteImport } from './routes/photo.$id'
import { Route as RollIndexRouteImport } from './routes/roll.index'
import { Route as RollIdRouteImport } from './routes/roll.$id'
import { Route as RollImportRouteImport } from './routes/roll.import'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BaselineRoute = BaselineRouteImport.update({
  id: '/baseline',
  path: '/baseline',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotoIdRoute = PhotoIdRouteImport.update({
  id: '/photo/$id',
  path: '/photo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RollIndexRoute = RollIndexRouteImport.update({
  id: '/roll/',
  path: '/roll/',
  getParentRoute: () => rootRouteImport,
} as any)
const RollIdRoute = RollIdRouteImport.update({
  id: '/roll/$id',
  path: '/roll/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RollImportRoute = RollImportRouteImport.update({
  id: '/roll/import',
  path: '/roll/import',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/baseline': typeof BaselineRoute
  '/upload': typeof UploadRoute
  '/photo/$id': typeof PhotoIdRoute
  '/roll/$id': typeof RollIdRoute
  '/roll/import': typeof RollImportRoute
  '/roll/': typeof RollIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/baseline': typeof BaselineRoute
  '/upload': typeof UploadRoute
  '/photo/$id': typeof PhotoIdRoute
  '/roll/$id': typeof RollIdRoute
  '/roll/import': typeof RollImportRoute
  '/roll': typeof RollIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/baseline': typeof BaselineRoute
  '/upload': typeof UploadRoute
  '/photo/$id': typeof PhotoIdRoute
  '/roll/$id': typeof RollIdRoute
  '/roll/import': typeof RollImportRoute
  '/roll/': typeof RollIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/baseline'
    | '/upload'
    | '/photo/$id'
    | '/roll/$id'
    | '/roll/import'
    | '/roll/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/baseline'
    | '/upload'
    | '/photo/$id'
    | '/roll/$id'
    | '/roll/import'
    | '/roll'
  id:
    | '__root__'
    | '/'
    | '/baseline'
    | '/upload'
    | '/photo/$id'
    | '/roll/$id'
    | '/roll/import'
    | '/roll/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BaselineRoute: typeof BaselineRoute
  UploadRoute: typeof UploadRoute
  PhotoIdRoute: typeof PhotoIdRoute
  RollIdRoute: typeof RollIdRoute
  RollImportRoute: typeof RollImportRoute
  RollIndexRoute: typeof RollIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baseline': {
      id: '/baseline'
      path: '/baseline'
      fullPath: '/baseline'
      preLoaderRoute: typeof BaselineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photo/$id': {
      id: '/photo/$id'
      path: '/photo/$id'
      fullPath: '/photo/$id'
      preLoaderRoute: typeof PhotoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roll/': {
      id: '/roll/'
      path: '/roll'
      fullPath: '/roll/'
      preLoaderRoute: typeof RollIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roll/$id': {
      id: '/roll/$id'
      path: '/roll/$id'
      fullPath: '/roll/$id'
      preLoaderRoute: typeof RollIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roll/import': {
      id: '/roll/import'
      path: '/roll/import'
      fullPath: '/roll/import'
      preLoaderRoute: typeof RollImportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BaselineRoute: BaselineRoute,
  UploadRoute: UploadRoute,
  PhotoIdRoute: PhotoIdRoute,
  RollIdRoute: RollIdRoute,
  RollImportRoute: RollImportRoute,
  RollIndexRoute: RollIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
