/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BaselineRouteImport } from './routes/baseline'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as DevExportRollRouteImport } from './routes/dev.export-roll'
import { Route as DevGipfelbuchLiveRouteImport } from './routes/dev.gipfelbuch-live'
import { Route as DevGipfelbuchSheetRouteImport } from './routes/dev.gipfelbuch-sheet'
import { Route as DevGraphRouteImport } from './routes/dev.graph'
import { Route as DevHowSceneRouteImport } from './routes/dev.how-scene'
import { Route as DevMetaRouteImport } from './routes/dev.meta'
import { Route as DevTafelRouteImport } from './routes/dev.tafel'
import { Route as GipfelbuchIndexRouteImport } from './routes/gipfelbuch.index'
import { Route as GipfelbuchConceptRouteImport } from './routes/gipfelbuch.$concept'
import { Route as GipfelbuchPrintRouteImport } from './routes/gipfelbuch.print'
import { Route as LabDeckSplatsRouteImport } from './routes/lab.deck-splats'
import { Route as LabDeckWebgpuRouteImport } from './routes/lab.deck-webgpu'
import { Route as LabGenerateRouteImport } from './routes/lab.generate'
import { Route as LabSplatsRouteImport } from './routes/lab.splats'
import { Route as PhotoIdRouteImport } from './routes/photo.$id'
import { Route as RollIndexRouteImport } from './routes/roll.index'
import { Route as RollIdRouteImport } from './routes/roll.$id'
import { Route as RollImportRouteImport } from './routes/roll.import'
import { Route as SCodeRouteImport } from './routes/s.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BaselineRoute = BaselineRouteImport.update({
  id: '/baseline',
  path: '/baseline',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const DevExportRollRoute = DevExportRollRouteImport.update({
  id: '/dev/export-roll',
  path: '/dev/export-roll',
  getParentRoute: () => rootRouteImport,
} as any)
const DevGipfelbuchLiveRoute = DevGipfelbuchLiveRouteImport.update({
  id: '/dev/gipfelbuch-live',
  path: '/dev/gipfelbuch-live',
  getParentRoute: () => rootRouteImport,
} as any)
const DevGipfelbuchSheetRoute = DevGipfelbuchSheetRouteImport.update({
  id: '/dev/gipfelbuch-sheet',
  path: '/dev/gipfelbuch-sheet',
  getParentRoute: () => rootRouteImport,
} as any)
const DevGraphRoute = DevGraphRouteImport.update({
  id: '/dev/graph',
  path: '/dev/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const DevHowSceneRoute = DevHowSceneRouteImport.update({
  id: '/dev/how-scene',
  path: '/dev/how-scene',
  getParentRoute: () => rootRouteImport,
} as any)
const DevMetaRoute = DevMetaRouteImport.update({
  id: '/dev/meta',
  path: '/dev/meta',
  getParentRoute: () => rootRouteImport,
} as any)
const DevTafelRoute = DevTafelRouteImport.update({
  id: '/dev/tafel',
  path: '/dev/tafel',
  getParentRoute: () => rootRouteImport,
} as any)
const GipfelbuchIndexRoute = GipfelbuchIndexRouteImport.update({
  id: '/gipfelbuch/',
  path: '/gipfelbuch/',
  getParentRoute: () => rootRouteImport,
} as any)
const GipfelbuchConceptRoute = GipfelbuchConceptRouteImport.update({
  id: '/gipfelbuch/$concept',
  path: '/gipfelbuch/$concept',
  getParentRoute: () => rootRouteImport,
} as any)
const GipfelbuchPrintRoute = GipfelbuchPrintRouteImport.update({
  id: '/gipfelbuch/print',
  path: '/gipfelbuch/print',
  getParentRoute: () => rootRouteImport,
} as any)
const LabDeckSplatsRoute = LabDeckSplatsRouteImport.update({
  id: '/lab/deck-splats',
  path: '/lab/deck-splats',
  getParentRoute: () => rootRouteImport,
} as any)
const LabDeckWebgpuRoute = LabDeckWebgpuRouteImport.update({
  id: '/lab/deck-webgpu',
  path: '/lab/deck-webgpu',
  getParentRoute: () => rootRouteImport,
} as any)
const LabGenerateRoute = LabGenerateRouteImport.update({
  id: '/lab/generate',
  path: '/lab/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const LabSplatsRoute = LabSplatsRouteImport.update({
  id: '/lab/splats',
  path: '/lab/splats',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotoIdRoute = PhotoIdRouteImport.update({
  id: '/photo/$id',
  path: '/photo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RollIndexRoute = RollIndexRouteImport.update({
  id: '/roll/',
  path: '/roll/',
  getParentRoute: () => rootRouteImport,
} as any)
const RollIdRoute = RollIdRouteImport.update({
  id: '/roll/$id',
  path: '/roll/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RollImportRoute = RollImportRouteImport.update({
  id: '/roll/import',
  path: '/roll/import',
  getParentRoute: () => rootRouteImport,
} as any)
const SCodeRoute = SCodeRouteImport.update({
  id: '/s/$code',
  path: '/s/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/baseline': typeof BaselineRoute
  '/library': typeof LibraryRoute
  '/upload': typeof UploadRoute
  '/dev/export-roll': typeof DevExportRollRoute
  '/dev/gipfelbuch-live': typeof DevGipfelbuchLiveRoute
  '/dev/gipfelbuch-sheet': typeof DevGipfelbuchSheetRoute
  '/dev/graph': typeof DevGraphRoute
  '/dev/how-scene': typeof DevHowSceneRoute
  '/dev/meta': typeof DevMetaRoute
  '/dev/tafel': typeof DevTafelRoute
  '/gipfelbuch/$concept': typeof GipfelbuchConceptRoute
  '/gipfelbuch/print': typeof GipfelbuchPrintRoute
  '/lab/deck-splats': typeof LabDeckSplatsRoute
  '/lab/deck-webgpu': typeof LabDeckWebgpuRoute
  '/lab/generate': typeof LabGenerateRoute
  '/lab/splats': typeof LabSplatsRoute
  '/photo/$id': typeof PhotoIdRoute
  '/roll/$id': typeof RollIdRoute
  '/roll/import': typeof RollImportRoute
  '/s/$code': typeof SCodeRoute
  '/gipfelbuch/': typeof GipfelbuchIndexRoute
  '/roll/': typeof RollIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/baseline': typeof BaselineRoute
  '/library': typeof LibraryRoute
  '/upload': typeof UploadRoute
  '/dev/export-roll': typeof DevExportRollRoute
  '/dev/gipfelbuch-live': typeof DevGipfelbuchLiveRoute
  '/dev/gipfelbuch-sheet': typeof DevGipfelbuchSheetRoute
  '/dev/graph': typeof DevGraphRoute
  '/dev/how-scene': typeof DevHowSceneRoute
  '/dev/meta': typeof DevMetaRoute
  '/dev/tafel': typeof DevTafelRoute
  '/gipfelbuch/$concept': typeof GipfelbuchConceptRoute
  '/gipfelbuch/print': typeof GipfelbuchPrintRoute
  '/lab/deck-splats': typeof LabDeckSplatsRoute
  '/lab/deck-webgpu': typeof LabDeckWebgpuRoute
  '/lab/generate': typeof LabGenerateRoute
  '/lab/splats': typeof LabSplatsRoute
  '/photo/$id': typeof PhotoIdRoute
  '/roll/$id': typeof RollIdRoute
  '/roll/import': typeof RollImportRoute
  '/s/$code': typeof SCodeRoute
  '/gipfelbuch': typeof GipfelbuchIndexRoute
  '/roll': typeof RollIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/baseline': typeof BaselineRoute
  '/library': typeof LibraryRoute
  '/upload': typeof UploadRoute
  '/dev/export-roll': typeof DevExportRollRoute
  '/dev/gipfelbuch-live': typeof DevGipfelbuchLiveRoute
  '/dev/gipfelbuch-sheet': typeof DevGipfelbuchSheetRoute
  '/dev/graph': typeof DevGraphRoute
  '/dev/how-scene': typeof DevHowSceneRoute
  '/dev/meta': typeof DevMetaRoute
  '/dev/tafel': typeof DevTafelRoute
  '/gipfelbuch/$concept': typeof GipfelbuchConceptRoute
  '/gipfelbuch/print': typeof GipfelbuchPrintRoute
  '/lab/deck-splats': typeof LabDeckSplatsRoute
  '/lab/deck-webgpu': typeof LabDeckWebgpuRoute
  '/lab/generate': typeof LabGenerateRoute
  '/lab/splats': typeof LabSplatsRoute
  '/photo/$id': typeof PhotoIdRoute
  '/roll/$id': typeof RollIdRoute
  '/roll/import': typeof RollImportRoute
  '/s/$code': typeof SCodeRoute
  '/gipfelbuch/': typeof GipfelbuchIndexRoute
  '/roll/': typeof RollIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/baseline'
    | '/library'
    | '/upload'
    | '/dev/export-roll'
    | '/dev/gipfelbuch-live'
    | '/dev/gipfelbuch-sheet'
    | '/dev/graph'
    | '/dev/how-scene'
    | '/dev/meta'
    | '/dev/tafel'
    | '/gipfelbuch/$concept'
    | '/gipfelbuch/print'
    | '/lab/deck-splats'
    | '/lab/deck-webgpu'
    | '/lab/generate'
    | '/lab/splats'
    | '/photo/$id'
    | '/roll/$id'
    | '/roll/import'
    | '/s/$code'
    | '/gipfelbuch/'
    | '/roll/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/baseline'
    | '/library'
    | '/upload'
    | '/dev/export-roll'
    | '/dev/gipfelbuch-live'
    | '/dev/gipfelbuch-sheet'
    | '/dev/graph'
    | '/dev/how-scene'
    | '/dev/meta'
    | '/dev/tafel'
    | '/gipfelbuch/$concept'
    | '/gipfelbuch/print'
    | '/lab/deck-splats'
    | '/lab/deck-webgpu'
    | '/lab/generate'
    | '/lab/splats'
    | '/photo/$id'
    | '/roll/$id'
    | '/roll/import'
    | '/s/$code'
    | '/gipfelbuch'
    | '/roll'
  id:
    | '__root__'
    | '/'
    | '/baseline'
    | '/library'
    | '/upload'
    | '/dev/export-roll'
    | '/dev/gipfelbuch-live'
    | '/dev/gipfelbuch-sheet'
    | '/dev/graph'
    | '/dev/how-scene'
    | '/dev/meta'
    | '/dev/tafel'
    | '/gipfelbuch/$concept'
    | '/gipfelbuch/print'
    | '/lab/deck-splats'
    | '/lab/deck-webgpu'
    | '/lab/generate'
    | '/lab/splats'
    | '/photo/$id'
    | '/roll/$id'
    | '/roll/import'
    | '/s/$code'
    | '/gipfelbuch/'
    | '/roll/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BaselineRoute: typeof BaselineRoute
  LibraryRoute: typeof LibraryRoute
  UploadRoute: typeof UploadRoute
  DevExportRollRoute: typeof DevExportRollRoute
  DevGipfelbuchLiveRoute: typeof DevGipfelbuchLiveRoute
  DevGipfelbuchSheetRoute: typeof DevGipfelbuchSheetRoute
  DevGraphRoute: typeof DevGraphRoute
  DevHowSceneRoute: typeof DevHowSceneRoute
  DevMetaRoute: typeof DevMetaRoute
  DevTafelRoute: typeof DevTafelRoute
  GipfelbuchConceptRoute: typeof GipfelbuchConceptRoute
  GipfelbuchPrintRoute: typeof GipfelbuchPrintRoute
  LabDeckSplatsRoute: typeof LabDeckSplatsRoute
  LabDeckWebgpuRoute: typeof LabDeckWebgpuRoute
  LabGenerateRoute: typeof LabGenerateRoute
  LabSplatsRoute: typeof LabSplatsRoute
  PhotoIdRoute: typeof PhotoIdRoute
  RollIdRoute: typeof RollIdRoute
  RollImportRoute: typeof RollImportRoute
  SCodeRoute: typeof SCodeRoute
  GipfelbuchIndexRoute: typeof GipfelbuchIndexRoute
  RollIndexRoute: typeof RollIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baseline': {
      id: '/baseline'
      path: '/baseline'
      fullPath: '/baseline'
      preLoaderRoute: typeof BaselineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/export-roll': {
      id: '/dev/export-roll'
      path: '/dev/export-roll'
      fullPath: '/dev/export-roll'
      preLoaderRoute: typeof DevExportRollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/gipfelbuch-live': {
      id: '/dev/gipfelbuch-live'
      path: '/dev/gipfelbuch-live'
      fullPath: '/dev/gipfelbuch-live'
      preLoaderRoute: typeof DevGipfelbuchLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/gipfelbuch-sheet': {
      id: '/dev/gipfelbuch-sheet'
      path: '/dev/gipfelbuch-sheet'
      fullPath: '/dev/gipfelbuch-sheet'
      preLoaderRoute: typeof DevGipfelbuchSheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/graph': {
      id: '/dev/graph'
      path: '/dev/graph'
      fullPath: '/dev/graph'
      preLoaderRoute: typeof DevGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/how-scene': {
      id: '/dev/how-scene'
      path: '/dev/how-scene'
      fullPath: '/dev/how-scene'
      preLoaderRoute: typeof DevHowSceneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/meta': {
      id: '/dev/meta'
      path: '/dev/meta'
      fullPath: '/dev/meta'
      preLoaderRoute: typeof DevMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/tafel': {
      id: '/dev/tafel'
      path: '/dev/tafel'
      fullPath: '/dev/tafel'
      preLoaderRoute: typeof DevTafelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gipfelbuch/': {
      id: '/gipfelbuch/'
      path: '/gipfelbuch'
      fullPath: '/gipfelbuch/'
      preLoaderRoute: typeof GipfelbuchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gipfelbuch/$concept': {
      id: '/gipfelbuch/$concept'
      path: '/gipfelbuch/$concept'
      fullPath: '/gipfelbuch/$concept'
      preLoaderRoute: typeof GipfelbuchConceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gipfelbuch/print': {
      id: '/gipfelbuch/print'
      path: '/gipfelbuch/print'
      fullPath: '/gipfelbuch/print'
      preLoaderRoute: typeof GipfelbuchPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/deck-splats': {
      id: '/lab/deck-splats'
      path: '/lab/deck-splats'
      fullPath: '/lab/deck-splats'
      preLoaderRoute: typeof LabDeckSplatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/deck-webgpu': {
      id: '/lab/deck-webgpu'
      path: '/lab/deck-webgpu'
      fullPath: '/lab/deck-webgpu'
      preLoaderRoute: typeof LabDeckWebgpuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/generate': {
      id: '/lab/generate'
      path: '/lab/generate'
      fullPath: '/lab/generate'
      preLoaderRoute: typeof LabGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/splats': {
      id: '/lab/splats'
      path: '/lab/splats'
      fullPath: '/lab/splats'
      preLoaderRoute: typeof LabSplatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photo/$id': {
      id: '/photo/$id'
      path: '/photo/$id'
      fullPath: '/photo/$id'
      preLoaderRoute: typeof PhotoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roll/': {
      id: '/roll/'
      path: '/roll'
      fullPath: '/roll/'
      preLoaderRoute: typeof RollIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roll/$id': {
      id: '/roll/$id'
      path: '/roll/$id'
      fullPath: '/roll/$id'
      preLoaderRoute: typeof RollIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roll/import': {
      id: '/roll/import'
      path: '/roll/import'
      fullPath: '/roll/import'
      preLoaderRoute: typeof RollImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$code': {
      id: '/s/$code'
      path: '/s/$code'
      fullPath: '/s/$code'
      preLoaderRoute: typeof SCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BaselineRoute: BaselineRoute,
  LibraryRoute: LibraryRoute,
  UploadRoute: UploadRoute,
  DevExportRollRoute: DevExportRollRoute,
  DevGipfelbuchLiveRoute: DevGipfelbuchLiveRoute,
  DevGipfelbuchSheetRoute: DevGipfelbuchSheetRoute,
  DevGraphRoute: DevGraphRoute,
  DevHowSceneRoute: DevHowSceneRoute,
  DevMetaRoute: DevMetaRoute,
  DevTafelRoute: DevTafelRoute,
  GipfelbuchConceptRoute: GipfelbuchConceptRoute,
  GipfelbuchPrintRoute: GipfelbuchPrintRoute,
  LabDeckSplatsRoute: LabDeckSplatsRoute,
  LabDeckWebgpuRoute: LabDeckWebgpuRoute,
  LabGenerateRoute: LabGenerateRoute,
  LabSplatsRoute: LabSplatsRoute,
  PhotoIdRoute: PhotoIdRoute,
  RollIdRoute: RollIdRoute,
  RollImportRoute: RollImportRoute,
  SCodeRoute: SCodeRoute,
  GipfelbuchIndexRoute: GipfelbuchIndexRoute,
  RollIndexRoute: RollIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
